#!/bin/zsh -f

echo -en "Connection: close\r\n"
echo -en "Content-type: application/octet-stream\r\n\r\n"

sleep 2 ## Enough time for the client to die
dd if=/dev/urandom ibs=50K count=1 2> /dev/null | base64
