#!/bin/zsh -f

# Point values
## PART 1
MAX_GET_CORRECT=15  # 1a
MAX_GET_HEADER=5   # 1b
MAX_GET_ROB_SYNT=10 # 1c
MAX_GET_ROB_CONN=10 # 1d
MAX_GET_CHUNK=10    # 1e
(( MAX_GET = MAX_GET_CORRECT + MAX_GET_HEADER + MAX_GET_ROB_CONN + MAX_GET_ROB_SYNT + MAX_GET_CHUNK ))

## PART 2
MAX_POST_CORRECT=20  # 2a
MAX_POST_ROB_CONN=5 # 2b
MAX_POST_ROB_SYNT=5 # 2c
(( MAX_POST = MAX_POST_ROB_SYNT + MAX_POST_ROB_CONN + MAX_POST_CORRECT ))

## PART 3
MAX_CONC_TWO=10       # 3a
MAX_CONC_MANY=10      # 3b
(( MAX_CONC = MAX_CONC_TWO + MAX_CONC_MANY ))

## BONUS PART
MAX_CACHE_TINY_DIES=8 # Ba
MAX_CACHE_400K=8      # Bb
MAX_CACHE_90K=8       # Bc
MAX_CACHE_BIG=10       # Bd
MAX_POST_CHUNK=16     # Be

(( MAX_BONUS = MAX_POST_CHUNK + MAX_CACHE_TINY_DIES + MAX_CACHE_400K + MAX_CACHE_90K + MAX_CACHE_BIG ))

MAX_SCORE=$((MAX_GET + MAX_POST + MAX_CONC ))
